// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_score__80 = "CgkIn6aa-LAPEAIQBA"; // <GPGSID>
        public const string achievement_score__20 = "CgkIn6aa-LAPEAIQAQ"; // <GPGSID>
        public const string achievement_score__100 = "CgkIn6aa-LAPEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_score_leaders = "CgkIn6aa-LAPEAIQBg"; // <GPGSID>
        public const string achievement_score__60 = "CgkIn6aa-LAPEAIQAw"; // <GPGSID>
        public const string achievement_score__40 = "CgkIn6aa-LAPEAIQAg"; // <GPGSID>

}

